Update TheRock ref to 52a8fda94bdab0fe93adcfb0d5ea233fb13dda1a due to rocm-libraries update

diff --git a/.github/workflows/therock-ci-nightly.yml b/.github/workflows/therock-ci-nightly.yml
--- a/.github/workflows/therock-ci-nightly.yml
+++ b/.github/workflows/therock-ci-nightly.yml
@@ -2,12 +2,13 @@ name: TheRock CI Nightly
 
 on:
   schedule:
-    - cron: "0 7 * * *" # Runs nightly at 7 AM UTC
+  - cron: "0 7 * * *"   # Runs nightly at 7 AM UTC
   workflow_dispatch:
     inputs:
       projects:
         type: string
-        description: "Insert space-separated list of projects to test or 'all' to test all projects. ex: 'projects/rocprim projects/hipcub'"
+        description: "Insert space-separated list of projects to test or 'all' to
+          test all projects. ex: 'projects/rocprim projects/hipcub'"
 
 permissions:
   contents: read
@@ -20,73 +21,76 @@ jobs:
       linux_projects: ${{ steps.linux_projects.outputs.linux_projects }}
       windows_projects: ${{ steps.windows_projects.outputs.windows_projects }}
       test_type: ${{ steps.linux_projects.outputs.test_type }}
-      linux_package_targets: ${{ steps.configure_linux.outputs.package_targets }}
-      windows_package_targets: ${{ steps.configure_windows.outputs.package_targets }}
+      linux_package_targets: ${{ steps.configure_linux.outputs.package_targets
+        }}
+      windows_package_targets: ${{
+        steps.configure_windows.outputs.package_targets }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-        with:
-          sparse-checkout: .github
-          sparse-checkout-cone-mode: true
-          fetch-depth: 2
+    - name: Checkout code
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
+      with:
+        sparse-checkout: .github
+        sparse-checkout-cone-mode: true
+        fetch-depth: 2
 
-      - name: Checkout TheRock repository
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-        with:
-          repository: "ROCm/TheRock"
-          path: TheRock
-          ref: 085571a87f8050f94c77eb90454995b6d1b75658 # 2026-02-26
+    - name: Checkout TheRock repository
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
+      with:
+        repository: "ROCm/TheRock"
+        path: TheRock
+        ref: 52a8fda94bdab0fe93adcfb0d5ea233fb13dda1a   # 2026-02-26
 
-      - name: Set up Python
-        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
-        with:
-          python-version: "3.12"
+    - name: Set up Python
+      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c   # v6.0.0
+      with:
+        python-version: "3.12"
 
-      - name: Install python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pydantic requests
+    - name: Install python dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pydantic requests
 
-      - name: Determine Linux projects to run
-        id: linux_projects
-        env:
-          PROJECTS: ${{ inputs.projects }}
-          PLATFORM: "linux"
-        run: |
-          python .github/scripts/therock_configure_ci.py
+    - name: Determine Linux projects to run
+      id: linux_projects
+      env:
+        PROJECTS: ${{ inputs.projects }}
+        PLATFORM: "linux"
+      run: |
+        python .github/scripts/therock_configure_ci.py
 
-      - name: Determine Windows projects to run
-        id: windows_projects
-        env:
-          PROJECTS: ${{ inputs.projects }}
-          PLATFORM: "windows"
-        run: |
-          python .github/scripts/therock_configure_ci.py
+    - name: Determine Windows projects to run
+      id: windows_projects
+      env:
+        PROJECTS: ${{ inputs.projects }}
+        PLATFORM: "windows"
+      run: |
+        python .github/scripts/therock_configure_ci.py
 
-      - name: Fetch Linux targets for build and test
-        env:
-          THEROCK_PACKAGE_PLATFORM: "linux"
+    - name: Fetch Linux targets for build and test
+      env:
+        THEROCK_PACKAGE_PLATFORM: "linux"
           # TODO(geomin12): Allow dynamic values of AMDGPU_FAMILIES, with opt-in options
-          AMDGPU_FAMILIES: "gfx94X, gfx950"
+        AMDGPU_FAMILIES: "gfx94X, gfx950"
           # Variable comes from ROCm organization variable 'ROCM_THEROCK_TEST_RUNNERS'
-          ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
-          LOAD_TEST_RUNNERS_FROM_VAR: true
-        id: configure_linux
-        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
+        ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
+        LOAD_TEST_RUNNERS_FROM_VAR: true
+      id: configure_linux
+      run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
 
-      - name: Fetch Windows targets for build and test
-        env:
-          THEROCK_PACKAGE_PLATFORM: "windows"
+    - name: Fetch Windows targets for build and test
+      env:
+        THEROCK_PACKAGE_PLATFORM: "windows"
           # TODO(geomin12): Allow dynamic values of AMDGPU_FAMILIES, with opt-in options
-          AMDGPU_FAMILIES: "gfx1151"
+        AMDGPU_FAMILIES: "gfx1151"
           # Variable comes from ROCm organization variable 'ROCM_THEROCK_TEST_RUNNERS'
-          ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
-          LOAD_TEST_RUNNERS_FROM_VAR: true
-        id: configure_windows
-        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
+        ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
+        LOAD_TEST_RUNNERS_FROM_VAR: true
+      id: configure_windows
+      run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
 
   therock-ci-linux:
-    name: Linux (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
+    name: Linux (${{ matrix.projects.projects_to_test }} | ${{
+      matrix.target_bundle.amdgpu_family }})
     permissions:
       contents: read
       id-token: write
@@ -96,7 +100,8 @@ jobs:
       fail-fast: false
       matrix:
         projects: ${{ fromJSON(needs.setup.outputs.linux_projects) }}
-        target_bundle: ${{ fromJSON(needs.setup.outputs.linux_package_targets) }}
+        target_bundle: ${{ fromJSON(needs.setup.outputs.linux_package_targets)
+          }}
     uses: ./.github/workflows/therock-ci-linux.yml
     secrets: inherit
     with:
@@ -107,7 +112,8 @@ jobs:
       test_runs_on: ${{ matrix.target_bundle.test_machine }}
 
   therock-ci-windows:
-    name: Windows (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
+    name: Windows (${{ matrix.projects.projects_to_test }} | ${{
+      matrix.target_bundle.amdgpu_family }})
     permissions:
       contents: read
       id-token: write
@@ -117,7 +123,8 @@ jobs:
       fail-fast: false
       matrix:
         projects: ${{ fromJSON(needs.setup.outputs.windows_projects) }}
-        target_bundle: ${{ fromJSON(needs.setup.outputs.windows_package_targets) }}
+        target_bundle: ${{ fromJSON(needs.setup.outputs.windows_package_targets)
+          }}
     uses: ./.github/workflows/therock-ci-windows.yml
     secrets: inherit
     with:
@@ -131,19 +138,19 @@ jobs:
     name: TheRock CI Nightly Summary
     if: always()
     needs:
-      - setup
-      - therock-ci-linux
-      - therock-ci-windows
+    - setup
+    - therock-ci-linux
+    - therock-ci-windows
     runs-on: ubuntu-24.04
     steps:
-      - name: Output failed jobs
-        run: |
-          echo '${{ toJson(needs) }}'
-          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
-            | jq --raw-output \
-            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
-          )"
-          if [[ "${FAILED_JOBS}" != "" ]]; then
-            echo "The following jobs failed: ${FAILED_JOBS}"
-            exit 1
-          fi
+    - name: Output failed jobs
+      run: |
+        echo '${{ toJson(needs) }}'
+        FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
+          | jq --raw-output \
+          'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
+        )"
+        if [[ "${FAILED_JOBS}" != "" ]]; then
+          echo "The following jobs failed: ${FAILED_JOBS}"
+          exit 1
+        fi
diff --git a/.github/workflows/therock-ci.yml b/.github/workflows/therock-ci.yml
--- a/.github/workflows/therock-ci.yml
+++ b/.github/workflows/therock-ci.yml
@@ -3,25 +3,28 @@ name: TheRock CI
 on:
   push:
     branches:
-      - develop
-      - release/therock-*
+    - develop
+    - release/therock-*
   pull_request:
     types:
-      - opened
-      - synchronize
-      - reopened
+    - opened
+    - synchronize
+    - reopened
   workflow_dispatch:
     inputs:
       projects:
         type: string
-        description: "Insert space-separated list of projects to test or 'all' to test all projects. ex: 'projects/rocprim projects/hipcub'"
+        description: "Insert space-separated list of projects to test or 'all' to
+          test all projects. ex: 'projects/rocprim projects/hipcub'"
       linux_amdgpu_families:
         type: string
-        description: "Insert comma-separated list of Linux GPU families to build and test. ex: gfx94X, gfx1151"
+        description: "Insert comma-separated list of Linux GPU families to build and
+          test. ex: gfx94X, gfx1151"
         default: ""
       windows_amdgpu_families:
         type: string
-        description: "Insert comma-separated list of Windows GPU families to build and test. ex: gfx94X, gfx1151"
+        description: "Insert comma-separated list of Windows GPU families to build
+          and test. ex: gfx94X, gfx1151"
         default: ""
   workflow_call:
 
@@ -44,85 +47,92 @@ jobs:
       linux_projects: ${{ steps.linux_projects.outputs.linux_projects }}
       windows_projects: ${{ steps.windows_projects.outputs.windows_projects }}
       test_type: ${{ steps.linux_projects.outputs.test_type }}
-      linux_package_targets: ${{ steps.configure_linux.outputs.package_targets }}
-      windows_package_targets: ${{ steps.configure_windows.outputs.package_targets }}
+      linux_package_targets: ${{ steps.configure_linux.outputs.package_targets
+        }}
+      windows_package_targets: ${{
+        steps.configure_windows.outputs.package_targets }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-        with:
-          sparse-checkout: .github
-          sparse-checkout-cone-mode: true
-          fetch-depth: 2
+    - name: Checkout code
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
+      with:
+        sparse-checkout: .github
+        sparse-checkout-cone-mode: true
+        fetch-depth: 2
 
-      - name: Checkout TheRock repository
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-        with:
-          repository: "ROCm/TheRock"
-          path: TheRock
-          ref: 085571a87f8050f94c77eb90454995b6d1b75658 # 2026-02-26
+    - name: Checkout TheRock repository
+      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
+      with:
+        repository: "ROCm/TheRock"
+        path: TheRock
+        ref: 52a8fda94bdab0fe93adcfb0d5ea233fb13dda1a   # 2026-02-26
 
-      - name: Set up Python
-        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
-        with:
-          python-version: "3.12"
+    - name: Set up Python
+      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c   # v6.0.0
+      with:
+        python-version: "3.12"
 
-      - name: Install python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pydantic requests
+    - name: Install python dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pydantic requests
 
-      - name: Set PR_LABELS variable with labels assigned to pull request
-        if: ${{ github.event.pull_request }} # only set PR labels var if this is a pull request
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-          PR_NUMBER: ${{ github.event.number }}
-        run: |
-          echo "PR_LABELS=$(gh pr view ${PR_NUMBER} --json labels)" >> $GITHUB_ENV
+    - name: Set PR_LABELS variable with labels assigned to pull request
+      if: ${{ github.event.pull_request }}   # only set PR labels var if this is a pull request
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+        PR_NUMBER: ${{ github.event.number }}
+      run: |
+        echo "PR_LABELS=$(gh pr view ${PR_NUMBER} --json labels)" >> $GITHUB_ENV
 
-      - name: Determine Linux projects to run
-        id: linux_projects
-        env:
-          PROJECTS: ${{ inputs.projects }}
-          PLATFORM: "linux"
-        run: |
-          python .github/scripts/therock_configure_ci.py
+    - name: Determine Linux projects to run
+      id: linux_projects
+      env:
+        PROJECTS: ${{ inputs.projects }}
+        PLATFORM: "linux"
+      run: |
+        python .github/scripts/therock_configure_ci.py
 
-      - name: Determine Windows projects to run
-        id: windows_projects
-        env:
-          PROJECTS: ${{ inputs.projects }}
-          PLATFORM: "windows"
-        run: |
-          python .github/scripts/therock_configure_ci.py
+    - name: Determine Windows projects to run
+      id: windows_projects
+      env:
+        PROJECTS: ${{ inputs.projects }}
+        PLATFORM: "windows"
+      run: |
+        python .github/scripts/therock_configure_ci.py
 
-      - name: Fetch Linux targets for build and test
-        env:
-          THEROCK_PACKAGE_PLATFORM: "linux"
-          AMDGPU_FAMILIES: ${{ inputs.linux_amdgpu_families || 'gfx94X, gfx950' }}
+    - name: Fetch Linux targets for build and test
+      env:
+        THEROCK_PACKAGE_PLATFORM: "linux"
+        AMDGPU_FAMILIES: ${{ inputs.linux_amdgpu_families || 'gfx94X, gfx950' }}
           # Variable comes from ROCm organization variable 'ROCM_THEROCK_TEST_RUNNERS'
-          ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
+        ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
           # TODO(#2656): Migrate the organization variable to S3 file. Below code is a temporary resolution
           # If it is a forked repo, we cannot access organization variables (so load in the file)
           # Otherwise, we use the organization variable directly
-          LOAD_TEST_RUNNERS_FROM_VAR: ${{ github.event.pull_request.head.repo.full_name == 'ROCm/rocm-libraries' }}
-        id: configure_linux
-        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
+        LOAD_TEST_RUNNERS_FROM_VAR: ${{
+          github.event.pull_request.head.repo.full_name == 'ROCm/rocm-libraries'
+          }}
+      id: configure_linux
+      run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
 
-      - name: Fetch Windows targets for build and test
-        env:
-          THEROCK_PACKAGE_PLATFORM: "windows"
-          AMDGPU_FAMILIES: ${{ inputs.windows_amdgpu_families || 'gfx1151' }}
+    - name: Fetch Windows targets for build and test
+      env:
+        THEROCK_PACKAGE_PLATFORM: "windows"
+        AMDGPU_FAMILIES: ${{ inputs.windows_amdgpu_families || 'gfx1151' }}
           # Variable comes from ROCm organization variable 'ROCM_THEROCK_TEST_RUNNERS'
-          ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
+        ROCM_THEROCK_TEST_RUNNERS: ${{ vars.ROCM_THEROCK_TEST_RUNNERS }}
           # TODO(#2656): Migrate the organization variable to S3 file. Below code is a temporary resolution
           # If it is a forked repo, we cannot access organization variables (so load in the file)
           # Otherwise, we use the organization variable directly
-          LOAD_TEST_RUNNERS_FROM_VAR: ${{ github.event.pull_request.head.repo.full_name == 'ROCm/rocm-libraries' }}
-        id: configure_windows
-        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
+        LOAD_TEST_RUNNERS_FROM_VAR: ${{
+          github.event.pull_request.head.repo.full_name == 'ROCm/rocm-libraries'
+          }}
+      id: configure_windows
+      run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py
 
   therock-ci-linux:
-    name: Linux (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
+    name: Linux (${{ matrix.projects.projects_to_test }} | ${{
+      matrix.target_bundle.amdgpu_family }})
     permissions:
       contents: read
       id-token: write
@@ -132,7 +142,8 @@ jobs:
       fail-fast: false
       matrix:
         projects: ${{ fromJSON(needs.setup.outputs.linux_projects) }}
-        target_bundle: ${{ fromJSON(needs.setup.outputs.linux_package_targets) }}
+        target_bundle: ${{ fromJSON(needs.setup.outputs.linux_package_targets)
+          }}
     uses: ./.github/workflows/therock-ci-linux.yml
     secrets: inherit
     with:
@@ -143,7 +154,8 @@ jobs:
       test_runs_on: ${{ matrix.target_bundle.test_machine }}
 
   therock-ci-windows:
-    name: Windows (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
+    name: Windows (${{ matrix.projects.projects_to_test }} | ${{
+      matrix.target_bundle.amdgpu_family }})
     permissions:
       contents: read
       id-token: write
@@ -153,7 +165,8 @@ jobs:
       fail-fast: false
       matrix:
         projects: ${{ fromJSON(needs.setup.outputs.windows_projects) }}
-        target_bundle: ${{ fromJSON(needs.setup.outputs.windows_package_targets) }}
+        target_bundle: ${{ fromJSON(needs.setup.outputs.windows_package_targets)
+          }}
     uses: ./.github/workflows/therock-ci-windows.yml
     secrets: inherit
     with:
@@ -167,19 +180,19 @@ jobs:
     name: TheRock CI Summary
     if: always()
     needs:
-      - setup
-      - therock-ci-linux
-      - therock-ci-windows
+    - setup
+    - therock-ci-linux
+    - therock-ci-windows
     runs-on: ubuntu-24.04
     steps:
-      - name: Output failed jobs
-        run: |
-          echo '${{ toJson(needs) }}'
-          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
-            | jq --raw-output \
-            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
-          )"
-          if [[ "${FAILED_JOBS}" != "" ]]; then
-            echo "The following jobs failed: ${FAILED_JOBS}"
-            exit 1
-          fi
+    - name: Output failed jobs
+      run: |
+        echo '${{ toJson(needs) }}'
+        FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
+          | jq --raw-output \
+          'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
+        )"
+        if [[ "${FAILED_JOBS}" != "" ]]; then
+          echo "The following jobs failed: ${FAILED_JOBS}"
+          exit 1
+        fi
